export const CAP_PERSONAL = "CAP_PERSONAL";
export const CAP_VEHICLE = "CAP_VEHICLE";
export const CAP_QUIZ = "CAP_QUIZ";
export const CAP_BROKERMANUAL = "CAP_BROKERMANUAL";
export const CAP_BROKERMANUALACK = "CAP_BROKERMANUALACK";
export const CAP_DIRECTDEPOSIT = "CAP_DIRECTDEPOSIT";
export const CAP_WSIB = "CAP_WSIB";
export const CAP_CONSENTFORM = "CAP_CONSENTFORM";
export const CAP_AODA = "CAP_AODA";
export const CAP_AODATEST = "CAP_AODATEST";
export const CAP_INTERVIEW = "CAP_INTERVIEW";
export const CAP_PAYMENT ="CAP_PAYMENT";


export const CHECKLIST_VEHICLELEASED = "VEHICLELEASED";
export const CHECKLIST_BACKGROUNDCHECK = "BACKGROUNDCHECK";
export const CHECKLIST_DRIVERSABSTRACT = "DRIVERSABSTRACT";
export const CHECKLIST_VEHICLEOWNED = "VEHICLEOWNED";